name: compras_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  http: ^1.3.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  particles_flutter: ^1.0.1
  flutter_svg: ^2.0.17
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.2.2

  timezone: ^0.9.2
  shared_preferences: ^2.5.2
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  assets:
    - assets/images/dog_soundboard.svg
    - lib/l10n/app_en.arb
    - lib/l10n/app_pt.arb
    - lib/l10n/app_es.arb
  uses-material-design: true